### ISSUE TITLE
CloudTrail "/" character

### ISSUE THREAD

**Issue by asikora** [easttimor/aws-incident-response#6]
Hi,

how did you handle the "/" character in the CloudTrail logs? The Athena doesn't support the "/" in column name and unfortunately there are "/" character in keys in json files from the ClouTrail.

**Comment by easttimor** [comment]
Help me understand better. The following WHERE clause, as an example, works.
userIdentity.arn = 'arn:aws:sts::111111111111:assumed-role/role_name/timothy.orr'

Perhaps I'm benefiting from the table creation, which is accomplished via CloudTrail Partitioner.
        query = """CREATE EXTERNAL TABLE IF NOT EXISTS `{table_name}` (
            `eventversion` string COMMENT 'from deserializer',
            `useridentity` struct<type:string,principalid:string,arn:string,accountid:string,invokedby:string,accesskeyid:string,username:string,sessioncontext:struct<attributes:struct<mfaauthenticated:string,creationdate:string>,sessionissuer:struct<type:string,principalid:string,arn:string,accountid:string,username:string>>> COMMENT 'from deserializer',
            `eventtime` string COMMENT 'from deserializer',
            `eventsource` string COMMENT 'from deserializer',
            `eventname` string COMMENT 'from deserializer',
            `awsregion` string COMMENT 'from deserializer',
            `sourceipaddress` string COMMENT 'from deserializer',
            `useragent` string COMMENT 'from deserializer',
            `errorcode` string COMMENT 'from deserializer',
            `errormessage` string COMMENT 'from deserializer',
            `requestparameters` string COMMENT 'from deserializer',
            `responseelements` string COMMENT 'from deserializer',
            `additionaleventdata` string COMMENT 'from deserializer',
            `requestid` string COMMENT 'from deserializer',
            `eventid` string COMMENT 'from deserializer',
            `resources` array<struct<arn:string,accountid:string,type:string>> COMMENT 'from deserializer',
            `eventtype` string COMMENT 'from deserializer',
            `apiversion` string COMMENT 'from deserializer',
            `readonly` string COMMENT 'from deserializer',
            `recipientaccountid` string COMMENT 'from deserializer',
            `serviceeventdetails` string COMMENT 'from deserializer',
            `sharedeventid` string COMMENT 'from deserializer',
            `vpcendpointid` string COMMENT 'from deserializer')
            PARTITIONED BY (region string, year string, month string, day string)
            ROW FORMAT SERDE
            'com.amazon.emr.hive.serde.CloudTrailSerde'
            STORED AS INPUTFORMAT
            'com.amazon.emr.cloudtrail.CloudTrailInputFormat'
            OUTPUTFORMAT
            'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
            LOCATION '{cloudtrail_log_path}'""".format(
            table_name=table_name, cloudtrail_log_path=cloudtrail_log_path
        )

**Comment by asikora** [comment]
Ok, the problem was I created the table using AWS Glue so for example the responseelements had type "struct" not string. When table is automatically created using AWS Glue the structures have "/" in column names which is not supported by the Athena. All is sorted now, thanks!

BTW, great repo! Thank you for sharing.

**Comment by easttimor** [comment]
Thank you. Please let me know if you find any parts of it useful, have questions, or have any ideas for fixes/enhancements.
